/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.ui;

/**
 *
 * @author luish
 */
import main.controller.CryptoController;
import main.exception.CryptoException;
import main.exception.InvalidKeyFormatException;
import main.exception.WrongKeyException;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.Component;
import java.io.IOException;



public class InterfazGrafica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGrafica.class.getName());
    
    private final CryptoController controller = new CryptoController();
    private String rutaOrigenTXT = "";
    private String rutaOrigenPEM = "";
    
    
    
    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(204, 153, 255));
        this.setLocationRelativeTo(null);
        
        //Seleccionar el RadioButton de Hide por default
        buttonEncrypt.setSelected(true);
        panelDecrypt.setEnabled(false);
        for(Component cp : panelDecrypt.getComponents()) cp.setEnabled(false);
        panelEncrypt.setEnabled(true);
        for(Component cp : panelEncrypt.getComponents()) cp.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupSeleccionModo = new javax.swing.ButtonGroup();
        titulo = new javax.swing.JLabel();
        buttonDecrypt = new javax.swing.JRadioButton();
        buttonEncrypt = new javax.swing.JRadioButton();
        panelEncrypt = new javax.swing.JPanel();
        buttonSelTXTEncrypt = new javax.swing.JButton();
        buttonEncryptFile = new javax.swing.JButton();
        buttonSelPemEncrypt = new javax.swing.JButton();
        panelDecrypt = new javax.swing.JPanel();
        buttonDecryptFile = new javax.swing.JButton();
        buttonSelTXTDecrypt = new javax.swing.JButton();
        buttonSelPemDecrypt = new javax.swing.JButton();
        Footer = new javax.swing.JLabel();
        buttonGenerateKeys = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 153, 255));

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        titulo.setText("4-RSA-File-Encryptor");

        buttonDecrypt.setBackground(new java.awt.Color(204, 153, 255));
        groupSeleccionModo.add(buttonDecrypt);
        buttonDecrypt.setText("Decrypt");
        buttonDecrypt.addActionListener(this::buttonDecryptActionPerformed);

        buttonEncrypt.setBackground(new java.awt.Color(204, 153, 255));
        groupSeleccionModo.add(buttonEncrypt);
        buttonEncrypt.setText("Encrypt");
        buttonEncrypt.addActionListener(this::buttonEncryptActionPerformed);

        panelEncrypt.setBackground(new java.awt.Color(204, 200, 255));
        panelEncrypt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelEncrypt.setForeground(new java.awt.Color(204, 200, 255));

        buttonSelTXTEncrypt.setText("Seleccionar .txt");
        buttonSelTXTEncrypt.addActionListener(this::buttonSelTXTEncryptActionPerformed);

        buttonEncryptFile.setBackground(new java.awt.Color(255, 0, 51));
        buttonEncryptFile.setForeground(new java.awt.Color(0, 0, 0));
        buttonEncryptFile.setText("Ejecutar Cifrado");
        buttonEncryptFile.addActionListener(this::buttonEncryptFileActionPerformed);

        buttonSelPemEncrypt.setText("Seleccionar .pem");
        buttonSelPemEncrypt.addActionListener(this::buttonSelPemEncryptActionPerformed);

        javax.swing.GroupLayout panelEncryptLayout = new javax.swing.GroupLayout(panelEncrypt);
        panelEncrypt.setLayout(panelEncryptLayout);
        panelEncryptLayout.setHorizontalGroup(
            panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncryptLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSelPemEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSelTXTEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncryptLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonEncryptFile)
                .addGap(36, 36, 36))
        );
        panelEncryptLayout.setVerticalGroup(
            panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncryptLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(buttonSelTXTEncrypt)
                .addGap(18, 18, 18)
                .addComponent(buttonSelPemEncrypt)
                .addGap(18, 18, 18)
                .addComponent(buttonEncryptFile)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelDecrypt.setBackground(new java.awt.Color(204, 200, 255));
        panelDecrypt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelDecrypt.setForeground(new java.awt.Color(204, 200, 255));

        buttonDecryptFile.setBackground(new java.awt.Color(51, 255, 0));
        buttonDecryptFile.setForeground(new java.awt.Color(0, 0, 0));
        buttonDecryptFile.setText("Ejecutar Descifrado");
        buttonDecryptFile.addActionListener(this::buttonDecryptFileActionPerformed);

        buttonSelTXTDecrypt.setText("Seleccionar .txt");
        buttonSelTXTDecrypt.addActionListener(this::buttonSelTXTDecryptActionPerformed);

        buttonSelPemDecrypt.setText("Seleccionar .pem");
        buttonSelPemDecrypt.addActionListener(this::buttonSelPemDecryptActionPerformed);

        javax.swing.GroupLayout panelDecryptLayout = new javax.swing.GroupLayout(panelDecrypt);
        panelDecrypt.setLayout(panelDecryptLayout);
        panelDecryptLayout.setHorizontalGroup(
            panelDecryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDecryptLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelDecryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonSelTXTDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDecryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buttonDecryptFile)
                        .addComponent(buttonSelPemDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelDecryptLayout.setVerticalGroup(
            panelDecryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDecryptLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(buttonSelTXTDecrypt)
                .addGap(18, 18, 18)
                .addComponent(buttonSelPemDecrypt)
                .addGap(18, 18, 18)
                .addComponent(buttonDecryptFile)
                .addGap(21, 21, 21))
        );

        Footer.setText("Developed by luisito2477-dev");

        buttonGenerateKeys.setBackground(new java.awt.Color(0, 204, 255));
        buttonGenerateKeys.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonGenerateKeys.setForeground(new java.awt.Color(0, 0, 0));
        buttonGenerateKeys.setText("Generar Llaves");
        buttonGenerateKeys.addActionListener(this::buttonGenerateKeysActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonEncrypt)
                                    .addComponent(panelEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonDecrypt)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(titulo)
                                .addGap(134, 134, 134))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Footer)
                            .addComponent(buttonGenerateKeys, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDecrypt)
                    .addComponent(buttonEncrypt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonGenerateKeys, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Footer)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //===BOTON PARA SELECCIONAR MODO DECRYPT
    private void buttonDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecryptActionPerformed
        panelEncrypt.setEnabled(false);
        panelDecrypt.setEnabled(true);
        
        for(Component cp : panelDecrypt.getComponents()) cp.setEnabled(true);
        for(Component cp : panelEncrypt.getComponents()) cp.setEnabled(false);
        
        rutaOrigenTXT = "";
        rutaOrigenPEM = "";
    }//GEN-LAST:event_buttonDecryptActionPerformed

    
    //===BOTON PARA SELECCIONAR TXT A CIFRAR
    private void buttonSelTXTEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelTXTEncryptActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos de Texto", "txt"));
        if (selector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            rutaOrigenTXT = selector.getSelectedFile().getAbsolutePath();
            JOptionPane.showMessageDialog(this, "TXT seleccionado: " + rutaOrigenTXT);
            
        }
    }//GEN-LAST:event_buttonSelTXTEncryptActionPerformed

    
    //===BOTON PARA CIFRAR ARCHIVO
    private void buttonEncryptFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEncryptFileActionPerformed
        if (rutaOrigenTXT.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona un archivo .txt.");
            return;
        }

        if (rutaOrigenPEM.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona un archivo .pem");
            return;
        }

        try {
            java.nio.file.Path output = controller.encrypt(rutaOrigenTXT, rutaOrigenPEM);
            JOptionPane.showMessageDialog(this, "Archivo cifrado exitosamente:\n" + output);

            rutaOrigenTXT = "";
            rutaOrigenPEM = "";

        } catch (WrongKeyException e) {
            JOptionPane.showMessageDialog(this,
                    "Llave incorrecta o archivo invalido",
                    "Error de seguridad",
                    JOptionPane.ERROR_MESSAGE);
        } catch (CryptoException e) {
            JOptionPane.showMessageDialog(this,
                    "Error de Cifrado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_buttonEncryptFileActionPerformed

    
    //===BOTON PARA DESCIFRAR ARCHIVO
    private void buttonDecryptFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecryptFileActionPerformed
        if (rutaOrigenTXT.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select a .txt file.");
            return;
        }

        if (rutaOrigenPEM.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select a .pem file.");
            return;
        }

        try {
            java.nio.file.Path output = controller.decrypt(rutaOrigenTXT, rutaOrigenPEM);
            JOptionPane.showMessageDialog(this, "Archivo descifrado exitosamente:\n" + output);

            rutaOrigenTXT = "";
            rutaOrigenPEM = "";

        } catch (WrongKeyException e) {
            JOptionPane.showMessageDialog(this,
                    "Llave incorrecta o archivo invalido",
                    "Error de seguridad",
                    JOptionPane.ERROR_MESSAGE);
        } catch (CryptoException e) {
            JOptionPane.showMessageDialog(this,
                    "Error de cifrado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonDecryptFileActionPerformed

    //===BOTON PARA SELECCIONAR MODO ENCRYPT
    private void buttonEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEncryptActionPerformed
        panelEncrypt.setEnabled(true);
        panelDecrypt.setEnabled(false);
        
        for(Component cp : panelDecrypt.getComponents()) cp.setEnabled(false);
        for(Component cp : panelEncrypt.getComponents()) cp.setEnabled(true);
        
        rutaOrigenTXT = "";
        rutaOrigenPEM = "";
    }//GEN-LAST:event_buttonEncryptActionPerformed

    
    //===BOTON PARA SELECCIONAR TXT A DESCIFRAR
    private void buttonSelTXTDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelTXTDecryptActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos de Texto", "txt"));
        if (selector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            rutaOrigenTXT = selector.getSelectedFile().getAbsolutePath();
            JOptionPane.showMessageDialog(this, "TXT seleccionado: " + rutaOrigenTXT);
            
        }
    }//GEN-LAST:event_buttonSelTXTDecryptActionPerformed

    //===BOTON PARA SELECCIONAR .PEM (LLAVE PUBLICA)
    private void buttonSelPemEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelPemEncryptActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos PEM", "pem"));
        if (selector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            rutaOrigenPEM = selector.getSelectedFile().getAbsolutePath();
            JOptionPane.showMessageDialog(this, "BEM seleccionado: " + rutaOrigenPEM);
            
        }
    }//GEN-LAST:event_buttonSelPemEncryptActionPerformed

    //===BOTON PARA SELECCIONAR .PEM (LLAVE PRIVADA)
    private void buttonSelPemDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelPemDecryptActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos PEM", "pem"));
        if (selector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            rutaOrigenPEM = selector.getSelectedFile().getAbsolutePath();
            JOptionPane.showMessageDialog(this, "BEM seleccionado: " + rutaOrigenPEM);
            
        }
    }//GEN-LAST:event_buttonSelPemDecryptActionPerformed

    //===BOTON PARA GENERAR LAS LLAVES/ARCHIVOS .PEM
    private void buttonGenerateKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerateKeysActionPerformed
        try {
            controller.generateKeys();
            JOptionPane.showMessageDialog(this, "Llaves generadas exitosamente dentro de la carpeta 'keys'");
        } catch (CryptoException e) {
            JOptionPane.showMessageDialog(this,
                    "Error generando las llaves: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonGenerateKeysActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Footer;
    private javax.swing.JRadioButton buttonDecrypt;
    private javax.swing.JButton buttonDecryptFile;
    private javax.swing.JRadioButton buttonEncrypt;
    private javax.swing.JButton buttonEncryptFile;
    private javax.swing.JButton buttonGenerateKeys;
    private javax.swing.JButton buttonSelPemDecrypt;
    private javax.swing.JButton buttonSelPemEncrypt;
    private javax.swing.JButton buttonSelTXTDecrypt;
    private javax.swing.JButton buttonSelTXTEncrypt;
    private javax.swing.ButtonGroup groupSeleccionModo;
    private javax.swing.JPanel panelDecrypt;
    private javax.swing.JPanel panelEncrypt;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
