/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author luish
 */
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.Component;



public class InterfazGrafica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGrafica.class.getName());
    
    
    
    
    
    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(204, 153, 255));
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupSeleccionModo = new javax.swing.ButtonGroup();
        titulo = new javax.swing.JLabel();
        panelEncrypt = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        alphaLabel = new javax.swing.JLabel();
        alphaField = new javax.swing.JTextField();
        betaLabel = new javax.swing.JLabel();
        betaField = new javax.swing.JTextField();
        nLabel = new javax.swing.JLabel();
        nField = new javax.swing.JTextField();
        obtFuncionesButton = new javax.swing.JButton();
        Footer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 153, 255));

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        titulo.setText("3-Affine-Cipher-Solver");

        panelEncrypt.setBackground(new java.awt.Color(204, 200, 255));
        panelEncrypt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelEncrypt.setForeground(new java.awt.Color(204, 200, 255));

        tituloLabel.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(0, 0, 0));
        tituloLabel.setText("Calculadora de Funciones Afines");

        alphaLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alphaLabel.setForeground(new java.awt.Color(0, 0, 0));
        alphaLabel.setText(" α:");

        alphaField.setText("2");
        alphaField.addActionListener(this::alphaFieldActionPerformed);

        betaLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        betaLabel.setForeground(new java.awt.Color(0, 0, 0));
        betaLabel.setText("β:");

        betaField.setText("3");
        betaField.addActionListener(this::betaFieldActionPerformed);

        nLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nLabel.setForeground(new java.awt.Color(0, 0, 0));
        nLabel.setText(" n:");

        nField.setText("26");
        nField.addActionListener(this::nFieldActionPerformed);

        obtFuncionesButton.setBackground(new java.awt.Color(102, 255, 102));
        obtFuncionesButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        obtFuncionesButton.setForeground(new java.awt.Color(0, 51, 0));
        obtFuncionesButton.setText("Obtener Funciones");
        obtFuncionesButton.addActionListener(this::obtFuncionesButtonActionPerformed);

        javax.swing.GroupLayout panelEncryptLayout = new javax.swing.GroupLayout(panelEncrypt);
        panelEncrypt.setLayout(panelEncryptLayout);
        panelEncryptLayout.setHorizontalGroup(
            panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncryptLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(panelEncryptLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelEncryptLayout.createSequentialGroup()
                        .addComponent(nLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelEncryptLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(betaLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(betaField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelEncryptLayout.createSequentialGroup()
                            .addComponent(alphaLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(alphaField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(obtFuncionesButton)
                .addGap(20, 20, 20))
        );
        panelEncryptLayout.setVerticalGroup(
            panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncryptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alphaLabel)
                    .addComponent(alphaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(betaLabel)
                    .addComponent(betaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obtFuncionesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nLabel)
                    .addComponent(nField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        Footer.setText("Developed by luisito2477-dev");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(panelEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(Footer)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titulo)
                .addGap(29, 29, 29)
                .addComponent(panelEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Footer)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alphaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alphaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alphaFieldActionPerformed

    private void betaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_betaFieldActionPerformed

    private void nFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nFieldActionPerformed

    private void obtFuncionesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtFuncionesButtonActionPerformed
        try {
            int alpha = Integer.parseInt(alphaField.getText());
            int beta = Integer.parseInt(betaField.getText());
            int n = Integer.parseInt(nField.getText());

            String resultado = CifradoDescifrado.obtenerFunciones(alpha, beta, n);

            // Mostrar en ventana emergente
            JOptionPane.showMessageDialog(this, resultado);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Ingresa solo números");
        }
    }//GEN-LAST:event_obtFuncionesButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Footer;
    private javax.swing.JTextField alphaField;
    private javax.swing.JLabel alphaLabel;
    private javax.swing.JTextField betaField;
    private javax.swing.JLabel betaLabel;
    private javax.swing.ButtonGroup groupSeleccionModo;
    private javax.swing.JTextField nField;
    private javax.swing.JLabel nLabel;
    private javax.swing.JButton obtFuncionesButton;
    private javax.swing.JPanel panelEncrypt;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
