/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author luish
 */
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.Component;



public class InterfazGrafica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGrafica.class.getName());
    
    private String rutaOrigen = "";
    
    
    
    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(204, 153, 255));
        this.setLocationRelativeTo(null);
        
        //Seleccionar la opcion 2x2 por default
        buttonOption2x2.setSelected(true);
        configurarDimensionMatriz(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupSeleccionModo = new javax.swing.ButtonGroup();
        titulo = new javax.swing.JLabel();
        buttonOption3x3 = new javax.swing.JRadioButton();
        buttonOption2x2 = new javax.swing.JRadioButton();
        panelEncrypt = new javax.swing.JPanel();
        matrixA_Label = new javax.swing.JLabel();
        matrixB_Label = new javax.swing.JLabel();
        mA_0_0_TextField = new javax.swing.JTextField();
        mA_0_1_TextField = new javax.swing.JTextField();
        mA_0_2_TextField = new javax.swing.JTextField();
        mA_1_0_TextField = new javax.swing.JTextField();
        mA_1_1_TextField = new javax.swing.JTextField();
        mA_1_2_TextField = new javax.swing.JTextField();
        mA_2_0_TextField = new javax.swing.JTextField();
        mA_2_1_TextField = new javax.swing.JTextField();
        mA_2_2_TextField = new javax.swing.JTextField();
        mB_0_0_TextField = new javax.swing.JTextField();
        mB_0_1_TextField = new javax.swing.JTextField();
        mB_0_2_TextField = new javax.swing.JTextField();
        mB_1_2_TextField = new javax.swing.JTextField();
        mB_2_2_TextField = new javax.swing.JTextField();
        mB_2_1_TextField = new javax.swing.JTextField();
        mB_1_1_TextField = new javax.swing.JTextField();
        mB_1_0_TextField = new javax.swing.JTextField();
        mB_2_0_TextField = new javax.swing.JTextField();
        matrixA_InvButton = new javax.swing.JButton();
        matrixB_InvButton = new javax.swing.JButton();
        dotA_B_Button = new javax.swing.JButton();
        dotB_A_Button = new javax.swing.JButton();
        nValueLabel = new javax.swing.JLabel();
        nValueField = new javax.swing.JTextField();
        Footer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 153, 255));

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        titulo.setText("5-Modular-Matrix-Toolbox");

        buttonOption3x3.setBackground(new java.awt.Color(204, 153, 255));
        groupSeleccionModo.add(buttonOption3x3);
        buttonOption3x3.setText("3x3");
        buttonOption3x3.addActionListener(this::buttonOption3x3ActionPerformed);

        buttonOption2x2.setBackground(new java.awt.Color(204, 153, 255));
        groupSeleccionModo.add(buttonOption2x2);
        buttonOption2x2.setText("2x2");
        buttonOption2x2.addActionListener(this::buttonOption2x2ActionPerformed);

        panelEncrypt.setBackground(new java.awt.Color(204, 200, 255));
        panelEncrypt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelEncrypt.setForeground(new java.awt.Color(204, 200, 255));

        matrixA_Label.setBackground(new java.awt.Color(204, 200, 255));
        matrixA_Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        matrixA_Label.setForeground(new java.awt.Color(0, 0, 0));
        matrixA_Label.setText("MATRIZ A");

        matrixB_Label.setBackground(new java.awt.Color(204, 200, 255));
        matrixB_Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        matrixB_Label.setForeground(new java.awt.Color(0, 0, 0));
        matrixB_Label.setText("MATRIZ B");

        mA_0_0_TextField.setText("0");

        mA_0_1_TextField.setText("0");

        mA_0_2_TextField.setText("0");

        mA_1_0_TextField.setText("0");

        mA_1_1_TextField.setText("0");

        mA_1_2_TextField.setText("0");

        mA_2_0_TextField.setText("0");

        mA_2_1_TextField.setText("0");

        mA_2_2_TextField.setText("0");

        mB_0_0_TextField.setText("0");

        mB_0_1_TextField.setText("0");

        mB_0_2_TextField.setText("0");

        mB_1_2_TextField.setText("0");

        mB_2_2_TextField.setText("0");

        mB_2_1_TextField.setText("0");

        mB_1_1_TextField.setText("0");

        mB_1_0_TextField.setText("0");

        mB_2_0_TextField.setText("0");

        matrixA_InvButton.setBackground(new java.awt.Color(51, 255, 204));
        matrixA_InvButton.setForeground(new java.awt.Color(0, 0, 0));
        matrixA_InvButton.setText("Matriz A inversa");
        matrixA_InvButton.addActionListener(this::matrixA_InvButtonActionPerformed);

        matrixB_InvButton.setBackground(new java.awt.Color(51, 255, 204));
        matrixB_InvButton.setForeground(new java.awt.Color(0, 0, 0));
        matrixB_InvButton.setText("Matriz B inversa");
        matrixB_InvButton.addActionListener(this::matrixB_InvButtonActionPerformed);

        dotA_B_Button.setBackground(new java.awt.Color(51, 255, 204));
        dotA_B_Button.setForeground(new java.awt.Color(0, 0, 0));
        dotA_B_Button.setText("A*B");
        dotA_B_Button.addActionListener(this::dotA_B_ButtonActionPerformed);

        dotB_A_Button.setBackground(new java.awt.Color(51, 255, 204));
        dotB_A_Button.setForeground(new java.awt.Color(0, 0, 0));
        dotB_A_Button.setText("B*A");
        dotB_A_Button.addActionListener(this::dotB_A_ButtonActionPerformed);

        nValueLabel.setBackground(new java.awt.Color(204, 200, 255));
        nValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nValueLabel.setForeground(new java.awt.Color(0, 0, 0));
        nValueLabel.setText("n:");

        nValueField.setText("0");

        javax.swing.GroupLayout panelEncryptLayout = new javax.swing.GroupLayout(panelEncrypt);
        panelEncrypt.setLayout(panelEncryptLayout);
        panelEncryptLayout.setHorizontalGroup(
            panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncryptLayout.createSequentialGroup()
                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelEncryptLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(matrixA_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(matrixB_Label)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEncryptLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEncryptLayout.createSequentialGroup()
                                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelEncryptLayout.createSequentialGroup()
                                        .addComponent(mA_0_0_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mA_0_1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mA_0_2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelEncryptLayout.createSequentialGroup()
                                        .addComponent(mA_1_0_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mA_1_1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mA_1_2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelEncryptLayout.createSequentialGroup()
                                        .addComponent(mA_2_0_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mA_2_1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mA_2_2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelEncryptLayout.createSequentialGroup()
                                        .addComponent(mB_0_0_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mB_0_1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mB_0_2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelEncryptLayout.createSequentialGroup()
                                        .addComponent(mB_1_0_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mB_1_1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mB_1_2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelEncryptLayout.createSequentialGroup()
                                        .addComponent(mB_2_0_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mB_2_1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mB_2_2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelEncryptLayout.createSequentialGroup()
                                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dotA_B_Button)
                                    .addComponent(matrixA_InvButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelEncryptLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(matrixB_InvButton))
                                    .addComponent(dotB_A_Button)))
                            .addGroup(panelEncryptLayout.createSequentialGroup()
                                .addComponent(nValueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nValueField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(17, 17, 17))
        );
        panelEncryptLayout.setVerticalGroup(
            panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncryptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrixA_Label)
                    .addComponent(matrixB_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEncryptLayout.createSequentialGroup()
                        .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mA_0_0_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mA_0_1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mA_0_2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mA_1_0_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mA_1_1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mA_1_2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mA_2_0_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mA_2_1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mA_2_2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelEncryptLayout.createSequentialGroup()
                        .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mB_0_0_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mB_0_1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mB_0_2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mB_1_0_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mB_1_1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mB_1_2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mB_2_0_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mB_2_1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mB_2_2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nValueLabel)
                    .addComponent(nValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matrixA_InvButton)
                    .addComponent(matrixB_InvButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dotA_B_Button)
                    .addComponent(dotB_A_Button))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Footer.setText("Developed by luisito2477-dev");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(buttonOption2x2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonOption3x3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panelEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Footer)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOption2x2)
                    .addComponent(buttonOption3x3))
                .addGap(4, 4, 4)
                .addComponent(panelEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Footer)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Funcion para copiar la matriz en los campos
    private void setMatrizEnCampos(int[][] matriz, boolean esMatrizA) {
        if (matriz == null) return;

        javax.swing.JTextField[][] campos;

        if (esMatrizA) {
            campos = new javax.swing.JTextField[][] {
                {mA_0_0_TextField, mA_0_1_TextField, mA_0_2_TextField},
                {mA_1_0_TextField, mA_1_1_TextField, mA_1_2_TextField},
                {mA_2_0_TextField, mA_2_1_TextField, mA_2_2_TextField}
            };
        } else {
            campos = new javax.swing.JTextField[][] {
                {mB_0_0_TextField, mB_0_1_TextField, mB_0_2_TextField},
                {mB_1_0_TextField, mB_1_1_TextField, mB_1_2_TextField},
                {mB_2_0_TextField, mB_2_1_TextField, mB_2_2_TextField}
            };
        }

        int tam = matriz.length;

        for (int i = 0; i < tam; i++) {
            for (int j = 0; j < tam; j++) {
                campos[i][j].setText(String.valueOf(matriz[i][j]));
            }
        }
    }
    
    
    private void mostrarResultadoConOpciones(int[][] resultado, String mensaje) {
    String strMatriz = MatrixOperations.matrizAString(resultado);

    Object[] opciones = {"Guardar en A", "Guardar en B", "Cancelar"};

    int seleccion = JOptionPane.showOptionDialog(
        this,
        mensaje + "\n" + strMatriz,
        "Resultado",
        JOptionPane.DEFAULT_OPTION,
        JOptionPane.INFORMATION_MESSAGE,
        null,
        opciones,
        opciones[0]
    );

    if (seleccion == 0) {
        setMatrizEnCampos(resultado, true);
    } else if (seleccion == 1) {
        setMatrizEnCampos(resultado, false);
    }
}
    
    
    //Metodo aux para deshabilitar los TextFields dependiendo de la dimension seleccionada
    private void configurarDimensionMatriz(boolean es3x3) {
        // Matriz A 
        mA_0_2_TextField.setEnabled(es3x3); // Columna 3
        mA_1_2_TextField.setEnabled(es3x3); // Columna 3
        mA_2_0_TextField.setEnabled(es3x3); // Fila 3
        mA_2_1_TextField.setEnabled(es3x3); // Fila 3
        mA_2_2_TextField.setEnabled(es3x3); // Esquina 3x3

        // Matriz B 
        mB_0_2_TextField.setEnabled(es3x3);
        mB_1_2_TextField.setEnabled(es3x3);
        mB_2_0_TextField.setEnabled(es3x3);
        mB_2_1_TextField.setEnabled(es3x3);
        mB_2_2_TextField.setEnabled(es3x3);

        // Limpiar el texto
        if(!es3x3) {
            mA_0_2_TextField.setText("0"); mA_1_2_TextField.setText("0");
            mA_2_0_TextField.setText("0"); mA_2_1_TextField.setText("0");
            mA_2_2_TextField.setText("0");
            
            mB_0_2_TextField.setText("0"); mB_1_2_TextField.setText("0");
            mB_2_0_TextField.setText("0"); mB_2_1_TextField.setText("0");
            mB_2_2_TextField.setText("0");
            // ... lo mismo para la matriz B si gustas
        }
    }
    
    private int leerEntero(javax.swing.JTextField field, String nombre) {
        String texto = field.getText().trim();
        if (texto.isEmpty()) {
            throw new IllegalArgumentException("El campo " + nombre + " no puede estar vacio");
        }
        try {
            return Integer.parseInt(texto);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("El campo " + nombre + " debe ser un entero valido");
        }
}
    
    //Funcion para obtener la Matriz A del input del usuario
    private int[][] obtenerMatrizA(int n) {
        int tam = buttonOption2x2.isSelected() ? 2 : 3;
        int[][] matriz = new int[tam][tam];

        matriz[0][0] = leerEntero(mA_0_0_TextField, "A[0][0]") % n;
        matriz[0][1] = leerEntero(mA_0_1_TextField, "A[0][1]") % n;
        if (tam == 3) matriz[0][2] = leerEntero(mA_0_2_TextField, "A[0][2]") % n;

        matriz[1][0] = leerEntero(mA_1_0_TextField, "A[1][0]") % n;
        matriz[1][1] = leerEntero(mA_1_1_TextField, "A[1][1]") % n;
        if (tam == 3) matriz[1][2] = leerEntero(mA_1_2_TextField, "A[1][2]") % n;

        if (tam == 3) {
            matriz[2][0] = leerEntero(mA_2_0_TextField, "A[2][0]") % n;
            matriz[2][1] = leerEntero(mA_2_1_TextField, "A[2][1]") % n;
            matriz[2][2] = leerEntero(mA_2_2_TextField, "A[2][2]") % n;
        }

        return matriz;
    }
    
        //Funcion para obtener la Matriz A del input del usuario
    private int[][] obtenerMatrizB(int n) {
        int tam = buttonOption2x2.isSelected() ? 2 : 3;
        int[][] matriz = new int[tam][tam];

        matriz[0][0] = leerEntero(mB_0_0_TextField, "B[0][0]") % n;
        matriz[0][1] = leerEntero(mB_0_1_TextField, "B[0][1]") % n;
        if (tam == 3) matriz[0][2] = leerEntero(mB_0_2_TextField, "B[0][2]") % n;

        matriz[1][0] = leerEntero(mB_1_0_TextField, "B[1][0]") % n;
        matriz[1][1] = leerEntero(mB_1_1_TextField, "B[1][1]") % n;
        if (tam == 3) matriz[1][2] = leerEntero(mB_1_2_TextField, "B[1][2]") % n;

        if (tam == 3) {
            matriz[2][0] = leerEntero(mB_2_0_TextField, "B[2][0]") % n;
            matriz[2][1] = leerEntero(mB_2_1_TextField, "B[2][1]") % n;
            matriz[2][2] = leerEntero(mB_2_2_TextField, "B[2][2]") % n;
        }

        return matriz;
    }
    
    
  
    
    private int obtenerNValue(){
        try {
            int n = Integer.parseInt(nValueField.getText().trim());
            if (n <= 0) {
                throw new IllegalArgumentException("n debe ser mayor a 0");
            }
            return n;
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("n debe ser un entero valido");
        }
    }
    
    
    
    private void buttonOption3x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOption3x3ActionPerformed
        configurarDimensionMatriz(true);
    }//GEN-LAST:event_buttonOption3x3ActionPerformed

    private void buttonOption2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOption2x2ActionPerformed
        configurarDimensionMatriz(false);
    }//GEN-LAST:event_buttonOption2x2ActionPerformed

    private void matrixA_InvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrixA_InvButtonActionPerformed
        try {
            int n = obtenerNValue();
            int[][] matrizA = obtenerMatrizA(n);
            int[][] matrizInv = MatrixOperations.calcMatrizInv(matrizA, n);
            //String strMatriz = MatrixOperations.matrizAString(matrizInv);

            mostrarResultadoConOpciones(matrizInv, "A * B:");

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_matrixA_InvButtonActionPerformed

    private void matrixB_InvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrixB_InvButtonActionPerformed
        try {
            int n = obtenerNValue();
            int[][] matrizB = obtenerMatrizB(n);
            int[][] matrizInv = MatrixOperations.calcMatrizInv(matrizB, n);
            //String strMatriz = MatrixOperations.matrizAString(matrizInv);

            mostrarResultadoConOpciones(matrizInv, "B inversa:");

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_matrixB_InvButtonActionPerformed

    private void dotA_B_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotA_B_ButtonActionPerformed
        try {
            int n = obtenerNValue();
            int[][] matrizA = obtenerMatrizA(n);
            int[][] matrizB = obtenerMatrizB(n);
            int[][] matrizDot = MatrixOperations.multMatrices(matrizA, matrizB, n);
            

            mostrarResultadoConOpciones(matrizDot, "A * B:");

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_dotA_B_ButtonActionPerformed

    private void dotB_A_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotB_A_ButtonActionPerformed
        try {
            int n = obtenerNValue();
            int[][] matrizA = obtenerMatrizA(n);
            int[][] matrizB = obtenerMatrizB(n);
            int[][] matrizDot = MatrixOperations.multMatrices(matrizB, matrizA, n);
            String strMatriz = MatrixOperations.matrizAString(matrizDot);

            mostrarResultadoConOpciones(matrizDot, "B * A:");

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_dotB_A_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Footer;
    private javax.swing.JRadioButton buttonOption2x2;
    private javax.swing.JRadioButton buttonOption3x3;
    private javax.swing.JButton dotA_B_Button;
    private javax.swing.JButton dotB_A_Button;
    private javax.swing.ButtonGroup groupSeleccionModo;
    private javax.swing.JTextField mA_0_0_TextField;
    private javax.swing.JTextField mA_0_1_TextField;
    private javax.swing.JTextField mA_0_2_TextField;
    private javax.swing.JTextField mA_1_0_TextField;
    private javax.swing.JTextField mA_1_1_TextField;
    private javax.swing.JTextField mA_1_2_TextField;
    private javax.swing.JTextField mA_2_0_TextField;
    private javax.swing.JTextField mA_2_1_TextField;
    private javax.swing.JTextField mA_2_2_TextField;
    private javax.swing.JTextField mB_0_0_TextField;
    private javax.swing.JTextField mB_0_1_TextField;
    private javax.swing.JTextField mB_0_2_TextField;
    private javax.swing.JTextField mB_1_0_TextField;
    private javax.swing.JTextField mB_1_1_TextField;
    private javax.swing.JTextField mB_1_2_TextField;
    private javax.swing.JTextField mB_2_0_TextField;
    private javax.swing.JTextField mB_2_1_TextField;
    private javax.swing.JTextField mB_2_2_TextField;
    private javax.swing.JButton matrixA_InvButton;
    private javax.swing.JLabel matrixA_Label;
    private javax.swing.JButton matrixB_InvButton;
    private javax.swing.JLabel matrixB_Label;
    private javax.swing.JTextField nValueField;
    private javax.swing.JLabel nValueLabel;
    private javax.swing.JPanel panelEncrypt;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
