/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica1;

/**
 *
 * @author luish
 */
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.Component;



public class InterfazGrafica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGrafica.class.getName());
    
    private String rutaBMPHide = "";
    private String rutaTXT = "";
    private String rutaBMPShow = "";
    
    
    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(204, 153, 255));
        this.setLocationRelativeTo(null);
        
        //Seleccionar el RadioButton de Hide por default
        buttonHide.setSelected(true);
        panelShow.setEnabled(false);
        for(Component cp : panelShow.getComponents()) cp.setEnabled(false);
        panelHide.setEnabled(true);
        for(Component cp : panelHide.getComponents()) cp.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupSeleccionModo = new javax.swing.ButtonGroup();
        titulo = new javax.swing.JLabel();
        buttonShow = new javax.swing.JRadioButton();
        buttonHide = new javax.swing.JRadioButton();
        panelHide = new javax.swing.JPanel();
        buttonSelBMPHide = new javax.swing.JButton();
        buttonSelTXTHide = new javax.swing.JButton();
        buttonCrearImagen = new javax.swing.JButton();
        panelShow = new javax.swing.JPanel();
        buttonSelBMPShow = new javax.swing.JButton();
        buttonCrearTXT = new javax.swing.JButton();
        Footer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 153, 255));

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        titulo.setText("LSB-SteganoBMP");

        buttonShow.setBackground(new java.awt.Color(204, 153, 255));
        groupSeleccionModo.add(buttonShow);
        buttonShow.setText("Show");
        buttonShow.addActionListener(this::buttonShowActionPerformed);

        buttonHide.setBackground(new java.awt.Color(204, 153, 255));
        groupSeleccionModo.add(buttonHide);
        buttonHide.setText("Hide");
        buttonHide.addActionListener(this::buttonHideActionPerformed);

        panelHide.setBackground(new java.awt.Color(204, 200, 255));
        panelHide.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelHide.setForeground(new java.awt.Color(204, 200, 255));

        buttonSelBMPHide.setText("Seleccionar .bmp");
        buttonSelBMPHide.addActionListener(this::buttonSelBMPHideActionPerformed);

        buttonSelTXTHide.setText("Seleccionar .txt");
        buttonSelTXTHide.addActionListener(this::buttonSelTXTHideActionPerformed);

        buttonCrearImagen.setBackground(new java.awt.Color(255, 0, 51));
        buttonCrearImagen.setForeground(new java.awt.Color(0, 0, 0));
        buttonCrearImagen.setText("Ejecutar Cifrado");
        buttonCrearImagen.addActionListener(this::buttonCrearImagenActionPerformed);

        javax.swing.GroupLayout panelHideLayout = new javax.swing.GroupLayout(panelHide);
        panelHide.setLayout(panelHideLayout);
        panelHideLayout.setHorizontalGroup(
            panelHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHideLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonSelBMPHide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSelTXTHide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCrearImagen)
                .addGap(29, 29, 29))
        );
        panelHideLayout.setVerticalGroup(
            panelHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHideLayout.createSequentialGroup()
                .addGroup(panelHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHideLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonSelBMPHide)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSelTXTHide))
                    .addGroup(panelHideLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(buttonCrearImagen)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panelShow.setBackground(new java.awt.Color(204, 200, 255));
        panelShow.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelShow.setForeground(new java.awt.Color(204, 200, 255));

        buttonSelBMPShow.setText("Seleccionar .bmp");
        buttonSelBMPShow.addActionListener(this::buttonSelBMPShowActionPerformed);

        buttonCrearTXT.setBackground(new java.awt.Color(51, 255, 0));
        buttonCrearTXT.setForeground(new java.awt.Color(0, 0, 0));
        buttonCrearTXT.setText("Ejecutar Descifrado");
        buttonCrearTXT.addActionListener(this::buttonCrearTXTActionPerformed);

        javax.swing.GroupLayout panelShowLayout = new javax.swing.GroupLayout(panelShow);
        panelShow.setLayout(panelShowLayout);
        panelShowLayout.setHorizontalGroup(
            panelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShowLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(buttonSelBMPShow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(buttonCrearTXT)
                .addGap(18, 18, 18))
        );
        panelShowLayout.setVerticalGroup(
            panelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShowLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCrearTXT)
                    .addComponent(buttonSelBMPShow))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Footer.setText("Made by luisito2477-dev");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonHide)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(panelHide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(buttonShow)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(Footer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(titulo)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(buttonHide)
                .addGap(1, 1, 1)
                .addComponent(panelHide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonShow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Footer)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowActionPerformed
        panelHide.setEnabled(false);
        panelShow.setEnabled(true);
        
        for(Component cp : panelShow.getComponents()) cp.setEnabled(true);
        for(Component cp : panelHide.getComponents()) cp.setEnabled(false);
    }//GEN-LAST:event_buttonShowActionPerformed

    private void buttonSelTXTHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelTXTHideActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos de Texto", "txt"));
        if (selector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            rutaTXT = selector.getSelectedFile().getAbsolutePath();
            System.out.println("TXT seleccionado: " + rutaTXT);
        }
    }//GEN-LAST:event_buttonSelTXTHideActionPerformed

    private void buttonCrearImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearImagenActionPerformed
        if (rutaBMPHide.isEmpty() || rutaTXT.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona ambos archivos (BMP y TXT).");
        } else {
            String escritorio = System.getProperty("user.home") + "\\Documents\\";
            String rutaDestino = escritorio + "resultado_cifrado.bmp";
            CifradoDescifrado.crearImagen(rutaBMPHide, rutaTXT, rutaDestino);
            JOptionPane.showMessageDialog(this, "Imagen creada con exito en: " + rutaDestino);
        }
    }//GEN-LAST:event_buttonCrearImagenActionPerformed

    private void buttonCrearTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearTXTActionPerformed
        if (rutaBMPShow.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona el BMP que quieres descifrar.");
        } else {
            String escritorio = System.getProperty("user.home") + "\\Documents\\";
            String rutaDestino = escritorio + "texto_descifrado.txt";
            CifradoDescifrado.crearArchivoTexto(rutaBMPShow, rutaDestino);
            JOptionPane.showMessageDialog(this, "Mensaje extraido en: " + rutaDestino);
        }
    }//GEN-LAST:event_buttonCrearTXTActionPerformed

    private void buttonSelBMPHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelBMPHideActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes BMP", "bmp"));
        if (selector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            rutaBMPHide = selector.getSelectedFile().getAbsolutePath();
            System.out.println("BMP seleccionado: " + rutaBMPHide);
        }
    }//GEN-LAST:event_buttonSelBMPHideActionPerformed

    private void buttonSelBMPShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelBMPShowActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes BMP", "bmp"));
        if (selector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            rutaBMPShow = selector.getSelectedFile().getAbsolutePath();
            System.out.println("BMP seleccionado: " + rutaBMPShow);
        } 
    }//GEN-LAST:event_buttonSelBMPShowActionPerformed

    private void buttonHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHideActionPerformed
        panelHide.setEnabled(true);
        panelShow.setEnabled(false);
        // Tip: tienes que deshabilitar los componentes internos también
        for(Component cp : panelShow.getComponents()) cp.setEnabled(false);
        for(Component cp : panelHide.getComponents()) cp.setEnabled(true);
    }//GEN-LAST:event_buttonHideActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Footer;
    private javax.swing.JButton buttonCrearImagen;
    private javax.swing.JButton buttonCrearTXT;
    private javax.swing.JRadioButton buttonHide;
    private javax.swing.JButton buttonSelBMPHide;
    private javax.swing.JButton buttonSelBMPShow;
    private javax.swing.JButton buttonSelTXTHide;
    private javax.swing.JRadioButton buttonShow;
    private javax.swing.ButtonGroup groupSeleccionModo;
    private javax.swing.JPanel panelHide;
    private javax.swing.JPanel panelShow;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
