/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author luish
 */
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.Component;



public class InterfazGrafica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGrafica.class.getName());
    
    private String rutaOrigen = "";
    
    
    
    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(204, 153, 255));
        this.setLocationRelativeTo(null);
        
        //Seleccionar el RadioButton de Hide por default
        buttonEncrypt.setSelected(true);
        panelDecrypt.setEnabled(false);
        for(Component cp : panelDecrypt.getComponents()) cp.setEnabled(false);
        panelEncrypt.setEnabled(true);
        for(Component cp : panelEncrypt.getComponents()) cp.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupSeleccionModo = new javax.swing.ButtonGroup();
        titulo = new javax.swing.JLabel();
        buttonDecrypt = new javax.swing.JRadioButton();
        buttonEncrypt = new javax.swing.JRadioButton();
        panelEncrypt = new javax.swing.JPanel();
        buttonSelTXTEncrypt = new javax.swing.JButton();
        buttonEncryptFile = new javax.swing.JButton();
        labelKeyEncrypt = new javax.swing.JLabel();
        keyFieldEncrypt = new javax.swing.JPasswordField();
        panelDecrypt = new javax.swing.JPanel();
        buttonDecryptFile = new javax.swing.JButton();
        keyFieldDecrypt = new javax.swing.JPasswordField();
        buttonSelTXTDecrypt = new javax.swing.JButton();
        labelKeyDecrypt = new javax.swing.JLabel();
        Footer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 153, 255));

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        titulo.setText("AES-File-Encryption-Service");

        buttonDecrypt.setBackground(new java.awt.Color(204, 153, 255));
        groupSeleccionModo.add(buttonDecrypt);
        buttonDecrypt.setText("Decrypt");
        buttonDecrypt.addActionListener(this::buttonDecryptActionPerformed);

        buttonEncrypt.setBackground(new java.awt.Color(204, 153, 255));
        groupSeleccionModo.add(buttonEncrypt);
        buttonEncrypt.setText("Encrypt");
        buttonEncrypt.addActionListener(this::buttonEncryptActionPerformed);

        panelEncrypt.setBackground(new java.awt.Color(204, 200, 255));
        panelEncrypt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelEncrypt.setForeground(new java.awt.Color(204, 200, 255));

        buttonSelTXTEncrypt.setText("Seleccionar .txt");
        buttonSelTXTEncrypt.addActionListener(this::buttonSelTXTEncryptActionPerformed);

        buttonEncryptFile.setBackground(new java.awt.Color(255, 0, 51));
        buttonEncryptFile.setForeground(new java.awt.Color(0, 0, 0));
        buttonEncryptFile.setText("Ejecutar Cifrado");
        buttonEncryptFile.addActionListener(this::buttonEncryptFileActionPerformed);

        labelKeyEncrypt.setBackground(new java.awt.Color(204, 200, 255));
        labelKeyEncrypt.setForeground(new java.awt.Color(0, 0, 0));
        labelKeyEncrypt.setText("LLAVE:");

        keyFieldEncrypt.setColumns(10);
        keyFieldEncrypt.setText("ejemplo");

        javax.swing.GroupLayout panelEncryptLayout = new javax.swing.GroupLayout(panelEncrypt);
        panelEncrypt.setLayout(panelEncryptLayout);
        panelEncryptLayout.setHorizontalGroup(
            panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncryptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEncryptLayout.createSequentialGroup()
                        .addComponent(labelKeyEncrypt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keyFieldEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonSelTXTEncrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEncryptFile)
                .addGap(29, 29, 29))
        );
        panelEncryptLayout.setVerticalGroup(
            panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncryptLayout.createSequentialGroup()
                .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEncryptLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(buttonEncryptFile))
                    .addGroup(panelEncryptLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(buttonSelTXTEncrypt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelEncryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(keyFieldEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelKeyEncrypt))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelDecrypt.setBackground(new java.awt.Color(204, 200, 255));
        panelDecrypt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelDecrypt.setForeground(new java.awt.Color(204, 200, 255));

        buttonDecryptFile.setBackground(new java.awt.Color(51, 255, 0));
        buttonDecryptFile.setForeground(new java.awt.Color(0, 0, 0));
        buttonDecryptFile.setText("Ejecutar Descifrado");
        buttonDecryptFile.addActionListener(this::buttonDecryptFileActionPerformed);

        keyFieldDecrypt.setColumns(10);
        keyFieldDecrypt.setText("ejemplo");

        buttonSelTXTDecrypt.setText("Seleccionar .txt");
        buttonSelTXTDecrypt.addActionListener(this::buttonSelTXTDecryptActionPerformed);

        labelKeyDecrypt.setBackground(new java.awt.Color(204, 200, 255));
        labelKeyDecrypt.setForeground(new java.awt.Color(0, 0, 0));
        labelKeyDecrypt.setText("LLAVE:");

        javax.swing.GroupLayout panelDecryptLayout = new javax.swing.GroupLayout(panelDecrypt);
        panelDecrypt.setLayout(panelDecryptLayout);
        panelDecryptLayout.setHorizontalGroup(
            panelDecryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDecryptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDecryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDecryptLayout.createSequentialGroup()
                        .addComponent(labelKeyDecrypt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keyFieldDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(buttonSelTXTDecrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(buttonDecryptFile)
                .addGap(18, 18, 18))
        );
        panelDecryptLayout.setVerticalGroup(
            panelDecryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDecryptLayout.createSequentialGroup()
                .addGroup(panelDecryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDecryptLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(buttonDecryptFile))
                    .addGroup(panelDecryptLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(buttonSelTXTDecrypt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDecryptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(keyFieldDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelKeyDecrypt))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Footer.setText("Developed by luisito2477-dev");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonEncrypt)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(panelEncrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelDecrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(buttonDecrypt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(Footer)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonEncrypt)
                .addGap(1, 1, 1)
                .addComponent(panelEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonDecrypt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Footer)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecryptActionPerformed
        panelEncrypt.setEnabled(false);
        panelDecrypt.setEnabled(true);
        
        for(Component cp : panelDecrypt.getComponents()) cp.setEnabled(true);
        for(Component cp : panelEncrypt.getComponents()) cp.setEnabled(false);
        
        rutaOrigen = "";
    }//GEN-LAST:event_buttonDecryptActionPerformed

    private void buttonSelTXTEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelTXTEncryptActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos de Texto", "txt"));
        if (selector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            rutaOrigen = selector.getSelectedFile().getAbsolutePath();
            JOptionPane.showMessageDialog(this, "TXT seleccionado: " + rutaOrigen);
            
        }
    }//GEN-LAST:event_buttonSelTXTEncryptActionPerformed

    private void buttonEncryptFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEncryptFileActionPerformed
        String llave = new String(keyFieldEncrypt.getPassword());
        if (rutaOrigen.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona un archivo .txt");
        } else if(llave.isEmpty()){
            JOptionPane.showMessageDialog(this, "Escribe la llave.");
        } else {
            try {
                CifradoDescifrado.cifrarArchivo(rutaOrigen, llave);
                JOptionPane.showMessageDialog(this, "Archivo protegido con éxito.");
                rutaOrigen = "";
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cifrar: Verifica que el archivo no esté abierto en otro programa.");
            }
        }
    }//GEN-LAST:event_buttonEncryptFileActionPerformed

    private void buttonDecryptFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecryptFileActionPerformed
        String llave = new String(keyFieldDecrypt.getPassword());
        if (rutaOrigen.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona un archivo .txt");
        } else if(llave.isEmpty()){
            JOptionPane.showMessageDialog(this, "Escribe la llave");
        
        } else {
            try {
                CifradoDescifrado.descifrarArchivo(rutaOrigen, llave);
                JOptionPane.showMessageDialog(this, "Texto descifrado exitosamente");
                rutaOrigen = "";
            } catch (Exception e) {
                if (e.getMessage().equals("LLAVE_INCORRECTA")) {
                    JOptionPane.showMessageDialog(this, "Error, La llave es incorrecta o el archivo no es válido.", "Error de Seguridad", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_buttonDecryptFileActionPerformed

    private void buttonEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEncryptActionPerformed
        panelEncrypt.setEnabled(true);
        panelDecrypt.setEnabled(false);
        
        for(Component cp : panelDecrypt.getComponents()) cp.setEnabled(false);
        for(Component cp : panelEncrypt.getComponents()) cp.setEnabled(true);
        rutaOrigen = "";
    }//GEN-LAST:event_buttonEncryptActionPerformed

    private void buttonSelTXTDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelTXTDecryptActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos de Texto", "txt"));
        if (selector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            rutaOrigen = selector.getSelectedFile().getAbsolutePath();
            JOptionPane.showMessageDialog(this, "TXT seleccionado: " + rutaOrigen);
            
        }
    }//GEN-LAST:event_buttonSelTXTDecryptActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Footer;
    private javax.swing.JRadioButton buttonDecrypt;
    private javax.swing.JButton buttonDecryptFile;
    private javax.swing.JRadioButton buttonEncrypt;
    private javax.swing.JButton buttonEncryptFile;
    private javax.swing.JButton buttonSelTXTDecrypt;
    private javax.swing.JButton buttonSelTXTEncrypt;
    private javax.swing.ButtonGroup groupSeleccionModo;
    private javax.swing.JPasswordField keyFieldDecrypt;
    private javax.swing.JPasswordField keyFieldEncrypt;
    private javax.swing.JLabel labelKeyDecrypt;
    private javax.swing.JLabel labelKeyEncrypt;
    private javax.swing.JPanel panelDecrypt;
    private javax.swing.JPanel panelEncrypt;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
